apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: golangci-lint
  labels:
    app.kubernetes.io/version: "0.1"
  annotations:
    tekton.dev/pipelines.minVersion: "0.12.1"
    tekton.dev/tags: lint
    tekton.dev/displayName: "golangci lint"
spec:
  description: >-
    This Task is Golang task to validate Go projects.
  workspaces:
  - name: source
  steps:
  - name: quality
    image: docker.io/golang:latest
    workingDir: $(workspaces.source.path)
    script: |
      go test

