apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: build-and-push
spec:
  description: >-
    Build and push projects using Dockerfile
  workspaces:
  - name: source
  params:
  - name: name
    type: string
    default: ""
  - name: revision
    type: string
    default: ""
  steps:
  - name: build-and-push
    image: docker.io/docker:19-dind
    workingDir: $(workspaces.source.path)
    script: |
      docker login --username=mayconjrpacheco --password=23224c83-f9fd-4718-a99d-7b08ba951de9
      docker build -t mayconjrpacheco/pipes/$(params.name):$(params.revision) -f ./cmd/Dockerfile .
      docker push mayconjrpacheco/pipes/$(params.name):$(params.revision)

